name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

concurrency: release

permissions:
  contents: write
  id-token: write
  packages: read

jobs:
  pre-artefact-creation:
    name: Tasks to run before artefact creation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4.1.1
        with:
          ref: "main"
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Validate CHANGELOG
        uses: docker://ghcr.io/ponylang/release-bot-action:0.6.4
        with:
          entrypoint: pre-artefact-changelog-check

  build:
    runs-on: ubuntu-latest
    needs:
      - pre-artefact-creation
    container:
      image: ghcr.io/redvers/pony-dependency-builder:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: build-binary
        run: make

  trigger-release-announcement:
    name: Trigger release announcement
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          ref: "main"
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Trigger
        uses: docker://ghcr.io/ponylang/release-bot-action:0.6.4
        with:
          entrypoint: trigger-release-announcement
        env:
          GIT_USER_NAME: "redvers"
          GIT_USER_EMAIL: "red@contact.red"
